server:
  port: 8082
  
eureka:
  client:
    enabled: true
    registry-fetch-interval-seconds: 10
    initial-instance-info-replication-interval-seconds: 10
  instance:
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10

management:
  endpoint:
    web:
      exposure:
        include:["health", "info", "refresh"]

order-type: updated
